name: Velez

services:
  postgres:
    image: postgres:18
    container_name: velez_postgres
    environment:
      POSTGRES_PASSWORD: velez
    ports:
      - '25432:5432'
    volumes:
      - './local_data:/var/lib/postgresql'