---
server_url: http://vcn.redsock.ru

listen_addr: 0.0.0.0:8080
metrics_listen_addr: 127.0.0.1:9090
noise:
  private_key_path: /var/lib/headscale/noise_private.key

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48
  allocation: sequential

disable_check_updates: false

derp:
  server:
    enabled: true
    region_id: 1
    region_code: local
    region_name: "local-derp"
    stun_listen_addr: "0.0.0.0:3478"
    private_key_path: /var/lib/headscale/derp_private.key
  urls:
    - https://controlplane.tailscale.com/derpmap/default

ephemeral_node_inactivity_timeout: 30m

database:
  type: sqlite

  debug: false

  # GORM configuration settings.
  gorm:
    prepare_stmt: true
    parameterized_queries: true
    skip_err_record_not_found: true
    slow_threshold: 1000

  sqlite:
    path: /var/lib/headscale/db.sqlite
    write_ahead_log: true
    wal_autocheckpoint: 1000



log:
  level: info
  format: json

policy:
  mode: file
  path: "/etc/headscale/acl.json"

dns:
  magic_dns: false
  override_local_dns: false

unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"


logtail:
  enabled: false

randomize_client_port: false
